trigger: none

parameters:
  - name: projectName
    type: string

  - name: dockerfilePath
    type: string

  - name: contextPath
    type: string

  - name: imageRepository
    type: string

pool:
  vmImage: ubuntu-latest

jobs:
  - job: DockerBuildAndPush
    displayName: Building ${{ parameters.projectName }}
    steps:
      - checkout: self
      
      - task: Docker@2
        inputs:
          command: login
          containerRegistry: 'dersimabbas'
        displayName: 'Logging into Azure Container Registry'
      
      - task: Docker@2
        inputs:
          command: buildAndPush
          containerRegistry: 'dersimabbas'
          repository: ${{ parameters.imageRepository }}
          dockerfile: ${{ parameters.dockerfilePath }}
          buildContext: ${{ parameters.contextPath }}
          tags: 'latest'

