
parameters:
  - name: projectName
    type: string

  - name: dockerfilePath
    type: string

  - name: contextPath
    type: string

  - name: imageRepository
    type: string
  
  - name: repoAlias
    type: string

  - name: tag
    type: string

jobs:
  - job: DockerBuildAndPush
    displayName: Building ${{ parameters.projectName }}
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: ${{ parameters.repoAlias }}
      
      
      - task: Docker@2
        inputs:
          command: login
          containerRegistry: 'ACRBicep'
        displayName: 'Logging into Azure Container Registry'
      
      - task: Docker@2
        inputs:
          command: buildAndPush
          containerRegistry: 'ACRBicep'
          repository: ${{ parameters.imageRepository }}
          dockerfile: ${{ parameters.dockerfilePath }}
          buildContext: ${{ parameters.contextPath }}
          tags: 'latest'

