
pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: infra
      type: git
      name: team-bicep-infrastructure
      trigger: none

    - repository: Backend
      type: git
      name: team-bicep-backend
      ref: refs/heads/main
      trigger:
        branches:
          include:
            - main

    - repository: Frontend
      type: git
      name: team-bicep-frontend
      ref: refs/heads/main
      trigger:
        branches:
          include:
            - main

stages:

- stage: Backend
  displayName: 'Backend'
  jobs:
  - template: DockerBuildAndPush-template.yml@infra
    parameters:
      projectName: 'TeamBicep.WebApi'
      dockerfilePath: 'src/TeamBicep.WebApi/Dockerfile'
      contextPath: 'src/TeamBicep.WebApi'
      imageRepository: 'TeamBicep/Backend'
      repoAlias: 'Backend'

- stage: Frontend
  displayName: 'Building Frontend with docker'
  dependsOn: Backend
  jobs:
  - template: DockerBuildAndPush-template.yml@infra
    parameters:
      projectName: 'TeamBicep.WebApp'
      dockerfilePath: 'src/TeamBicep.WebApp/Dockerfile'
      contextPath: 'src/TeamBicep.WebApp'
      imageRepository: 'TeamBicep/Frontend'
      repoAlias: 'Frontend'

- stage: Infra
  displayName: 'Build Infra'
  dependsOn: Frontend
  jobs:
  - template: bicep-infra-create-template.yml@infra
    parameters:
      environment: 'prod'
      serviceConnectionName: 'biceparmconnection'
      resourceGroupName: 'RG-dersimabbas'
      useEnvironmentSuffix: false
      deploymentLocation: 'swedencentral'